#   From: https://github.com/MartinDbx/RDO-CollectorsShopToMap
#   File: Utilities/reader.py
#   Author: Martin Debaisieux
#   Date: 20 May 2024

import itemlib


def collectionsExtractor(fileName: str) -> list:
    """Retrieves from the file generated by 'index.html' the collections to
    which these items belong and returns the list of these collections."""

    collectionsToShow = []

    with open(fileName, 'r') as file:
        items = file.readlines()

        for collection in itemlib.COLLECTIONS:
            for item in items[:-1]:
                if item[:-1] in collection and collection[0] not in collectionsToShow:
                    collectionsToShow.append(collection[0])
                    break
            if items[-1] in collection and collection[0] not in collectionsToShow:
                 collectionsToShow.append(collection[0])

    return collectionsToShow


def itemsExtractor(fileName: str) -> list:
    """Retrieves the uncollected items generated by 'index.html' to create a
    list."""

    with open(fileName, 'r') as file:
        items = file.readlines()

        uncollectedItems = [item[:-1] for item in items[:-1]]
        uncollectedItems.append(items[-1])

    return uncollectedItems

